{
 "title": "Desafio Técnico",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Disponibilidade",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SUM(CASE\n      WHEN ligada AND operacao AND NOT manutencao_corretiva AND NOT manutencao_preventiva THEN 1\n      ELSE 0\n    END)/COUNT(*)::numeric) * 100.0 AS disponibilidade\nFROM dados_maquina\nWHERE $__timeFilter(datahora)"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(pecas_por_hora) AS performance\nFROM (\n  SELECT\n    date_trunc('hour', datahora) AS hora,\n    SUM(pecas_produzidas) AS pecas_por_hora\n  FROM dados_maquina\n  WHERE $__timeFilter(datahora)\n  GROUP BY hora\n) AS performance_por_hora"
    }
   ]
  },
  {
   "title": "Qualidade",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ((SUM(pecas_produzidas)-SUM(pecas_defeituosas))::numeric/NULLIF(SUM(pecas_produzidas),0))*100 AS qualidade\nFROM dados_maquina \nWHERE $__timeFilter(datahora)"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SUM(CASE\n      WHEN ligada AND operacao AND NOT manutencao_corretiva AND NOT manutencao_preventiva THEN 1\n      ELSE 0\n    END)/COUNT(*)::numeric) * 100.0 AS disponibilidade\nFROM dados_maquina\nWHERE $__timeFilter(datahora)"
    },
    {
     "rawSql": "SELECT\n  AVG(pecas_por_hora) AS performance\nFROM (\n  SELECT\n    date_trunc('hour', datahora) AS hora,\n    SUM(pecas_produzidas) AS pecas_por_hora\n  FROM dados_maquina\n  WHERE $__timeFilter(datahora)\n  GROUP BY hora\n) AS performance_por_hora"
    },
    {
     "rawSql": "SELECT\n  ((SUM(pecas_produzidas)-SUM(pecas_defeituosas))::numeric/NULLIF(SUM(pecas_produzidas),0))*100 AS qualidade\nFROM dados_maquina \nWHERE $__timeFilter(datahora)"
    },
    {
     "expression": "($performance/100)*($qualidade/100)*($disponibilidade/100)",
     "type": "math"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(pecas_produzidas) FROM dados_maquina WHERE $__timeFilter(datahora);"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(pecas_defeituosas) FROM dados_maquina WHERE $__timeFilter(datahora);"
    }
   ]
  }
 ]
}